### ISSUE TITLE
fmn.consumer is not Python 3 compatible

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn.consumer#95]
There are a few Python 3 incompatibilities the new unit tests revealed. Since Python 2's life is nearing an end, it's good to be ready for Python 3.

Current issues:

- [ ] Imports are broken on Python 3. For example:
```
ERROR: test_sse_backend (unittest.loader._FailedTest)

----------------------------------------------------------------------

ImportError: Failed to import test module: test_sse_backend

Traceback (most recent call last):

  File "/opt/python/3.5.2/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName

    module = __import__(module_name)

  File "/home/travis/build/fedora-infra/fmn.consumer/tests/test_sse_backend.py", line 11, in <module>

    from fmn.consumer.backends import SSEBackend

  File "/home/travis/build/fedora-infra/fmn.consumer/fmn/consumer/__init__.py", line 1, in <module>

    from .consumer import FMNConsumer  # noqa

  File "/home/travis/build/fedora-infra/fmn.consumer/fmn/consumer/consumer.py", line 11, in <module>

    import fmn.lib

ImportError: No module named 'fmn.lib'
```

- [ ] fmn.consumer/scripts/matchtest.py:67:14: E999 SyntaxError: invalid syntax

**Comment by pypingou** [comment]
Be ready agreed but we're still running on py2 in prod so we can't drop it yet :)
(just making sure it's known it even though I'm sure you're aware of it :))

**Comment by jeremycline** [comment]
Closing in favor of https://github.com/fedora-infra/fmn/issues/143
